# Generated by Django 3.1.2 on 2021-02-01 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.TextField(blank=True, null=True)),
                ('item_serial_no', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('unit', models.CharField(blank=True, max_length=10, null=True)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=8)),
                ('active_status', models.BooleanField(blank=True, default=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Materials',
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.CharField(blank=True, max_length=250, null=True, unique=True)),
                ('active_status', models.BooleanField(blank=True, default=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Topics',
            },
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_name', models.CharField(blank=True, max_length=500, null=True, unique=True)),
                ('submission_date', models.DateField(auto_now_add=True, null=True)),
                ('work_progress', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('active_status', models.BooleanField(blank=True, default=True, null=True)),
                ('materials', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materials_bill', to='dushanbe.material')),
                ('topics', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topics_bill', to='dushanbe.topic')),
            ],
            options={
                'verbose_name_plural': 'Topics',
            },
        ),
    ]
