# Generated by Django 3.1.2 on 2021-02-07 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dushanbe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billsubmission',
            name='bill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='billsubmission_bill', to='dushanbe.bill'),
        ),
    ]
