# Generated by Django 3.1.2 on 2021-02-14 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dushanbe', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='worksubmission',
            unique_together={('bill', 'type')},
        ),
    ]
