# Generated by Django 3.1.2 on 2021-02-10 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dushanbe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='type_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
