# Generated by Django 3.1.2 on 2021-02-09 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dushanbe', '0002_auto_20210207_0947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billsubmission',
            name='material',
        ),
        migrations.AddField(
            model_name='type',
            name='material',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='type_material', to='dushanbe.material'),
        ),
        migrations.AlterField(
            model_name='billsubmission',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billsubmission_type', to='dushanbe.type'),
        ),
    ]
