# Generated by Django 3.1.2 on 2021-02-14 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dushanbe', '0002_auto_20210214_1226'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='worksubmission',
            unique_together=set(),
        ),
    ]
