# Generated by Django 3.1.2 on 2021-02-16 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dushanbe', '0003_auto_20210214_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worksubmission',
            name='work_progress',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
