# Generated by Django 3.1.2 on 2021-02-03 10:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dushanbe', '0003_auto_20210202_1239'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materials_name', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Materials',
            },
        ),
        migrations.AddField(
            model_name='bill',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bill_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bill',
            name='created_datetime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='bill_name',
            field=models.CharField(blank=True, max_length=500, null=True, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='bill',
            unique_together=set(),
        ),
        migrations.CreateModel(
            name='NameOfWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_name', models.CharField(blank=True, max_length=250, null=True)),
                ('item_serial_no', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('unit', models.CharField(blank=True, max_length=10, null=True)),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('submission_date', models.DateField(auto_now_add=True, null=True)),
                ('work_progress', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('bill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nameofwork_bill', to='dushanbe.bill')),
                ('materials', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nameofwork_materials', to='dushanbe.material')),
            ],
            options={
                'verbose_name_plural': 'Name Of Work',
            },
        ),
        migrations.RemoveField(
            model_name='bill',
            name='item_serial_no',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='material_name',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='submission_date',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='topic_name',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='work_progress',
        ),
    ]
