# Generated by Django 3.1.2 on 2021-02-03 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dushanbe', '0004_auto_20210203_1605'),
    ]

    operations = [
        migrations.RenameField(
            model_name='material',
            old_name='materials_name',
            new_name='material_name',
        ),
        migrations.RenameField(
            model_name='nameofwork',
            old_name='materials',
            new_name='material',
        ),
    ]
