# Generated by Django 3.1.2 on 2021-02-22 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dushanbe', '0004_auto_20210216_1100'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='material',
            unique_together=set(),
        ),
    ]
