# Generated by Django 3.1.2 on 2021-02-03 11:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dushanbe', '0005_auto_20210203_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bill_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='nameofwork',
            name='material',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nameofwork_material', to='dushanbe.material'),
        ),
    ]
